name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          
      - run: |
          flutter pub get
          flutter clean
          flutter build web \
            --release \
            --base-href /flutter-crossword/ \
            --web-renderer html

      - name: Verify Build
        run: ls -la build/web/

      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
