name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]  # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Install dependencies
      - run: flutter pub get

      # 4. Build for web (replace YOUR-REPO-NAME)
      - run: flutter build web --release --base-href /flutter-crossword/

      # 5. Deploy to gh-pages branch
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true  # Keeps only latest deployment
